[tool.poetry]
name = "calculate-deposit"
version = "0.1.0"
description = ""
authors = ["Kvezac <Kvezak@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
